import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { db } from "@/lib/db";
import Image from "next/image";
import Logo from "@/assets/pictures/navbar-logo.webp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await db.user.findMany();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex w-full shadow-lg fixed">
          <Image src={Logo} alt="logo" width={180} height={180} />
        </nav>
        {children}
      </body>
    </html>
  );
}
